language: python
python:
  - "2.7"

env:
  global:
    - secure: "LHcJox+t+cqGLdNXK8kHegyNjPYn/zfj4lL2vH8r2pT0oC6wujPmOE5XlyyufYm67rYvySES4ds/mCTFtEduu33Am9uNlHrlKqoIk9SeAPJ2nNtVxppH/+F50C7RGB4hGc658RPXO7CDhHr0HtmkyibgFxXJDSxa4ULKsv7dU9Y="
    - secure: "LXM56uqDPtqdBdnZFTN+QMayz3eBX+BJNugMSMiVvGpxA34FMQxOPhRG6KMTx6WYglrS47upqfIatIVyOXw8pic7D+gDbdtHFfcuOeMq471VN1VD57UgIIjikSQcER1YRlANKw8LvkLh+YoVuCoPJ/xvSLTGrXC0z8XQMIn2KCM="

# whitelist
branches:
  only:
    - oschina

# Use this to prepare the system to install prerequisites or dependencies
before_install: "sudo apt-get update"

# command to install dependencies
install: "pip install -q -r requirements.txt --use-mirrors"

# command to build
script:
  - "make html-en"
  - "make html-zh"

after_success:
  - "tar -zcf cakephp-docs.tar.gz ./build/html"
  - "curl --ftp-create-dirs -u $FTP_USER:$FTP_PASSWORD -T cakephp-docs.tar.gz ftp://42.96.185.133/com.cakephpchina/"
