sudo: false

language: python
python:
  - "2.7"

# env:
#   global:
    # aliyun server ftp account
    # - secure: "LHcJox+t+cqGLdNXK8kHegyNjPYn/zfj4lL2vH8r2pT0oC6wujPmOE5XlyyufYm67rYvySES4ds/mCTFtEduu33Am9uNlHrlKqoIk9SeAPJ2nNtVxppH/+F50C7RGB4hGc658RPXO7CDhHr0HtmkyibgFxXJDSxa4ULKsv7dU9Y="
    # - secure: "LXM56uqDPtqdBdnZFTN+QMayz3eBX+BJNugMSMiVvGpxA34FMQxOPhRG6KMTx6WYglrS47upqfIatIVyOXw8pic7D+gDbdtHFfcuOeMq471VN1VD57UgIIjikSQcER1YRlANKw8LvkLh+YoVuCoPJ/xvSLTGrXC0z8XQMIn2KCM="

    # blue host ftp account
    # - secure: "g6l8QOueYUZLZH1FJuKB/LO+jKlhrKCPwkMfERGFY4SG6uTtHCm0M+YJYyb92YHJiSuQvLw6/oBLFtgbwy84EPmkOhGn/F1j/McgDCWZVGX2e4phkYeAFMtIkVkEpUc0sMBgeIPBIz8YgawUuM22N3x8/VHywk5CILx7hpa3oEY="
    # - secure: "X/yNqcublNpGEFKZWWlCEvTAcQx2TgT/K+Obv0k6zqvoF2D+bF28BPAPbZO/u3yMxYJtA4P6ZMEvxKLXggpKCmy9wDkbyUYEqZ4MtapxYa7JfVE+iMq5mCH3WLnpa8aIWA1w7ONQByZvUTqz7Ava3Rl47Gt6VVtBPUFNoKhk6Rw="

# whitelist
branches:
  only:
    - oschina

# Use this to prepare the system to install prerequisites or dependencies
# before_install: "sudo apt-get update"

# use addons.apt.packages to install package instead of using sudo
# addons:
#   apt:
#     packages:
#     - cmake

before_install:
  - openssl aes-256-cbc -K $encrypted_3e936d71521e_key -iv $encrypted_3e936d71521e_iv -in cakephpchina.deploy@github.com.enc -out cakephpchina.deploy@github.com -d
  - chmod 0600 cakephpchina.deploy@github.com

# command to install dependencies
install: pip install -q -r requirements.txt

# command to build
script:
  - make html-en
  - make html-zh

after_success:
  # for aliyun server
  # - "cd ./build"
  # - "tar -zcf cakephp-docs.tar.gz ./html"
  # - "curl --ftp-create-dirs -u $FTP_USER:$FTP_PASSWORD -T cakephp-docs.tar.gz ftp://42.96.185.133/com.cakephpchina/"

  # directly upload individual files
  # - "cd ./build/html"
  # - "find ./ -type f -exec curl --ftp-create-dirs -u $FTP_USER:$FTP_PASSWORD -T {} ftp://ftp.wengyuli.com/{} \\;"

  # deploy to GitHub Pages
  # - pwd  # /home/travis/build/blackpuppy/docs
  - cd ..
  - ssh-agent bash -c 'ssh-add ./docs/cakephpchina.deploy@github.com; git clone git@github.com:blackpuppy/cakephpchina.git'
  - cd cakephpchina
  - git config user.email "mingzhu.z+github@gmail.com"
  - git config user.name "Zhu Ming"
  - rm -rf en zh
  - cp -r ../docs/build/html/{en,zh} .
  - git add .
  - git commit -m "auto deployment to GitHub Pages by Travis CI"
  - ssh-agent bash -c 'ssh-add ../docs/cakephpchina.deploy@github.com; git push origin gh-pages'
